apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-29T10:49:36Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "2851"
  uid: 0deb1745-5f35-435a-a714-ad76f3d3b9b8
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.104.207.75
  clusterIPs:
  - 10.104.207.75
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32180
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
